[[headers]]
  for = "/*"
  [headers.values]
    # This is an extremely permissive policy. It allows scripts, styles,
    # images, etc., from any source.
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"
